// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuestionUseCase creates a new instance of MockQuestionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionUseCase {
	mock := &MockQuestionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuestionUseCase is an autogenerated mock type for the QuestionUseCase type
type MockQuestionUseCase struct {
	mock.Mock
}

type MockQuestionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionUseCase) EXPECT() *MockQuestionUseCase_Expecter {
	return &MockQuestionUseCase_Expecter{mock: &_m.Mock}
}

// CreateQuestion provides a mock function for the type MockQuestionUseCase
func (_mock *MockQuestionUseCase) CreateQuestion(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionUseCase_CreateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestion'
type MockQuestionUseCase_CreateQuestion_Call struct {
	*mock.Call
}

// CreateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionUseCase_Expecter) CreateQuestion(ctx interface{}, q interface{}) *MockQuestionUseCase_CreateQuestion_Call {
	return &MockQuestionUseCase_CreateQuestion_Call{Call: _e.mock.On("CreateQuestion", ctx, q)}
}

func (_c *MockQuestionUseCase_CreateQuestion_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionUseCase_CreateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionUseCase_CreateQuestion_Call) Return(err error) *MockQuestionUseCase_CreateQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionUseCase_CreateQuestion_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionUseCase_CreateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestion provides a mock function for the type MockQuestionUseCase
func (_mock *MockQuestionUseCase) DeleteQuestion(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionUseCase_DeleteQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestion'
type MockQuestionUseCase_DeleteQuestion_Call struct {
	*mock.Call
}

// DeleteQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionUseCase_Expecter) DeleteQuestion(ctx interface{}, id interface{}) *MockQuestionUseCase_DeleteQuestion_Call {
	return &MockQuestionUseCase_DeleteQuestion_Call{Call: _e.mock.On("DeleteQuestion", ctx, id)}
}

func (_c *MockQuestionUseCase_DeleteQuestion_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionUseCase_DeleteQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionUseCase_DeleteQuestion_Call) Return(err error) *MockQuestionUseCase_DeleteQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionUseCase_DeleteQuestion_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockQuestionUseCase_DeleteQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionByID provides a mock function for the type MockQuestionUseCase
func (_mock *MockQuestionUseCase) GetQuestionByID(ctx context.Context, id domain.ID) (*domain.Question, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionByID")
	}

	var r0 *domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.Question, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.Question); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionUseCase_GetQuestionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionByID'
type MockQuestionUseCase_GetQuestionByID_Call struct {
	*mock.Call
}

// GetQuestionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionUseCase_Expecter) GetQuestionByID(ctx interface{}, id interface{}) *MockQuestionUseCase_GetQuestionByID_Call {
	return &MockQuestionUseCase_GetQuestionByID_Call{Call: _e.mock.On("GetQuestionByID", ctx, id)}
}

func (_c *MockQuestionUseCase_GetQuestionByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionUseCase_GetQuestionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionUseCase_GetQuestionByID_Call) Return(question *domain.Question, err error) *MockQuestionUseCase_GetQuestionByID_Call {
	_c.Call.Return(question, err)
	return _c
}

func (_c *MockQuestionUseCase_GetQuestionByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.Question, error)) *MockQuestionUseCase_GetQuestionByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuestion provides a mock function for the type MockQuestionUseCase
func (_mock *MockQuestionUseCase) UpdateQuestion(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuestion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionUseCase_UpdateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuestion'
type MockQuestionUseCase_UpdateQuestion_Call struct {
	*mock.Call
}

// UpdateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionUseCase_Expecter) UpdateQuestion(ctx interface{}, q interface{}) *MockQuestionUseCase_UpdateQuestion_Call {
	return &MockQuestionUseCase_UpdateQuestion_Call{Call: _e.mock.On("UpdateQuestion", ctx, q)}
}

func (_c *MockQuestionUseCase_UpdateQuestion_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionUseCase_UpdateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionUseCase_UpdateQuestion_Call) Return(err error) *MockQuestionUseCase_UpdateQuestion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionUseCase_UpdateQuestion_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionUseCase_UpdateQuestion_Call {
	_c.Call.Return(run)
	return _c
}
