// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	"github.com/Valery223/Question-Bank/internal/usecase/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuestionRepository creates a new instance of MockQuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionRepository {
	mock := &MockQuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuestionRepository is an autogenerated mock type for the QuestionRepository type
type MockQuestionRepository struct {
	mock.Mock
}

type MockQuestionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionRepository) EXPECT() *MockQuestionRepository_Expecter {
	return &MockQuestionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Create(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQuestionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionRepository_Expecter) Create(ctx interface{}, q interface{}) *MockQuestionRepository_Create_Call {
	return &MockQuestionRepository_Create_Call{Call: _e.mock.On("Create", ctx, q)}
}

func (_c *MockQuestionRepository_Create_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Create_Call) Return(err error) *MockQuestionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Delete(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQuestionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockQuestionRepository_Delete_Call {
	return &MockQuestionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockQuestionRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Delete_Call) Return(err error) *MockQuestionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockQuestionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Filter(ctx context.Context, filter ports.QuestionFilter) ([]domain.Question, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QuestionFilter) ([]domain.Question, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QuestionFilter) []domain.Question); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.QuestionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockQuestionRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.QuestionFilter
func (_e *MockQuestionRepository_Expecter) Filter(ctx interface{}, filter interface{}) *MockQuestionRepository_Filter_Call {
	return &MockQuestionRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter)}
}

func (_c *MockQuestionRepository_Filter_Call) Run(run func(ctx context.Context, filter ports.QuestionFilter)) *MockQuestionRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.QuestionFilter
		if args[1] != nil {
			arg1 = args[1].(ports.QuestionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Filter_Call) Return(questions []domain.Question, err error) *MockQuestionRepository_Filter_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestionRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter ports.QuestionFilter) ([]domain.Question, error)) *MockQuestionRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) GetByID(ctx context.Context, id domain.ID) (*domain.Question, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.Question, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.Question); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQuestionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockQuestionRepository_GetByID_Call {
	return &MockQuestionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQuestionRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_GetByID_Call) Return(question *domain.Question, err error) *MockQuestionRepository_GetByID_Call {
	_c.Call.Return(question, err)
	return _c
}

func (_c *MockQuestionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.Question, error)) *MockQuestionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) GetByIDs(ctx context.Context, ids []domain.ID) ([]domain.Question, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) ([]domain.Question, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) []domain.Question); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.ID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockQuestionRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.ID
func (_e *MockQuestionRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockQuestionRepository_GetByIDs_Call {
	return &MockQuestionRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockQuestionRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []domain.ID)) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ID
		if args[1] != nil {
			arg1 = args[1].([]domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_GetByIDs_Call) Return(questions []domain.Question, err error) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestionRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []domain.ID) ([]domain.Question, error)) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Update(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQuestionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionRepository_Expecter) Update(ctx interface{}, q interface{}) *MockQuestionRepository_Update_Call {
	return &MockQuestionRepository_Update_Call{Call: _e.mock.On("Update", ctx, q)}
}

func (_c *MockQuestionRepository_Update_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Update_Call) Return(err error) *MockQuestionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
