// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionUseCase creates a new instance of MockSessionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionUseCase {
	mock := &MockSessionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionUseCase is an autogenerated mock type for the SessionUseCase type
type MockSessionUseCase struct {
	mock.Mock
}

type MockSessionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionUseCase) EXPECT() *MockSessionUseCase_Expecter {
	return &MockSessionUseCase_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionUseCase
func (_mock *MockSessionUseCase) CreateSession(ctx context.Context, s *domain.TestSession) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestSession) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionUseCase_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionUseCase_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - s *domain.TestSession
func (_e *MockSessionUseCase_Expecter) CreateSession(ctx interface{}, s interface{}) *MockSessionUseCase_CreateSession_Call {
	return &MockSessionUseCase_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, s)}
}

func (_c *MockSessionUseCase_CreateSession_Call) Run(run func(ctx context.Context, s *domain.TestSession)) *MockSessionUseCase_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestSession
		if args[1] != nil {
			arg1 = args[1].(*domain.TestSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionUseCase_CreateSession_Call) Return(err error) *MockSessionUseCase_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionUseCase_CreateSession_Call) RunAndReturn(run func(ctx context.Context, s *domain.TestSession) error) *MockSessionUseCase_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByID provides a mock function for the type MockSessionUseCase
func (_mock *MockSessionUseCase) GetSessionByID(ctx context.Context, id domain.ID) (*domain.TestSession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *domain.TestSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestSession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestSession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionUseCase_GetSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByID'
type MockSessionUseCase_GetSessionByID_Call struct {
	*mock.Call
}

// GetSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockSessionUseCase_Expecter) GetSessionByID(ctx interface{}, id interface{}) *MockSessionUseCase_GetSessionByID_Call {
	return &MockSessionUseCase_GetSessionByID_Call{Call: _e.mock.On("GetSessionByID", ctx, id)}
}

func (_c *MockSessionUseCase_GetSessionByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockSessionUseCase_GetSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionUseCase_GetSessionByID_Call) Return(testSession *domain.TestSession, err error) *MockSessionUseCase_GetSessionByID_Call {
	_c.Call.Return(testSession, err)
	return _c
}

func (_c *MockSessionUseCase_GetSessionByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestSession, error)) *MockSessionUseCase_GetSessionByID_Call {
	_c.Call.Return(run)
	return _c
}
