// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTemplateUseCase creates a new instance of MockTemplateUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateUseCase {
	mock := &MockTemplateUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateUseCase is an autogenerated mock type for the TemplateUseCase type
type MockTemplateUseCase struct {
	mock.Mock
}

type MockTemplateUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateUseCase) EXPECT() *MockTemplateUseCase_Expecter {
	return &MockTemplateUseCase_Expecter{mock: &_m.Mock}
}

// CreateTemplate provides a mock function for the type MockTemplateUseCase
func (_mock *MockTemplateUseCase) CreateTemplate(ctx context.Context, t *domain.TestTemplate) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateUseCase_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockTemplateUseCase_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.TestTemplate
func (_e *MockTemplateUseCase_Expecter) CreateTemplate(ctx interface{}, t interface{}) *MockTemplateUseCase_CreateTemplate_Call {
	return &MockTemplateUseCase_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, t)}
}

func (_c *MockTemplateUseCase_CreateTemplate_Call) Run(run func(ctx context.Context, t *domain.TestTemplate)) *MockTemplateUseCase_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateUseCase_CreateTemplate_Call) Return(err error) *MockTemplateUseCase_CreateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateUseCase_CreateTemplate_Call) RunAndReturn(run func(ctx context.Context, t *domain.TestTemplate) error) *MockTemplateUseCase_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function for the type MockTemplateUseCase
func (_mock *MockTemplateUseCase) DeleteTemplate(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateUseCase_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockTemplateUseCase_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateUseCase_Expecter) DeleteTemplate(ctx interface{}, id interface{}) *MockTemplateUseCase_DeleteTemplate_Call {
	return &MockTemplateUseCase_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, id)}
}

func (_c *MockTemplateUseCase_DeleteTemplate_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateUseCase_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateUseCase_DeleteTemplate_Call) Return(err error) *MockTemplateUseCase_DeleteTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateUseCase_DeleteTemplate_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockTemplateUseCase_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateByID provides a mock function for the type MockTemplateUseCase
func (_mock *MockTemplateUseCase) GetTemplateByID(ctx context.Context, id domain.ID) (*domain.TestTemplate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 *domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestTemplate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestTemplate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateUseCase_GetTemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByID'
type MockTemplateUseCase_GetTemplateByID_Call struct {
	*mock.Call
}

// GetTemplateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateUseCase_Expecter) GetTemplateByID(ctx interface{}, id interface{}) *MockTemplateUseCase_GetTemplateByID_Call {
	return &MockTemplateUseCase_GetTemplateByID_Call{Call: _e.mock.On("GetTemplateByID", ctx, id)}
}

func (_c *MockTemplateUseCase_GetTemplateByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateUseCase_GetTemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateUseCase_GetTemplateByID_Call) Return(testTemplate *domain.TestTemplate, err error) *MockTemplateUseCase_GetTemplateByID_Call {
	_c.Call.Return(testTemplate, err)
	return _c
}

func (_c *MockTemplateUseCase_GetTemplateByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestTemplate, error)) *MockTemplateUseCase_GetTemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function for the type MockTemplateUseCase
func (_mock *MockTemplateUseCase) UpdateTemplate(ctx context.Context, t *domain.TestTemplate) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateUseCase_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type MockTemplateUseCase_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.TestTemplate
func (_e *MockTemplateUseCase_Expecter) UpdateTemplate(ctx interface{}, t interface{}) *MockTemplateUseCase_UpdateTemplate_Call {
	return &MockTemplateUseCase_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, t)}
}

func (_c *MockTemplateUseCase_UpdateTemplate_Call) Run(run func(ctx context.Context, t *domain.TestTemplate)) *MockTemplateUseCase_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateUseCase_UpdateTemplate_Call) Return(err error) *MockTemplateUseCase_UpdateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateUseCase_UpdateTemplate_Call) RunAndReturn(run func(ctx context.Context, t *domain.TestTemplate) error) *MockTemplateUseCase_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}
