// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	"github.com/Valery223/Question-Bank/internal/usecase/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Create(ctx context.Context, tt *domain.TestTemplate) error {
	ret := _mock.Called(ctx, tt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, tt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tt *domain.TestTemplate
func (_e *MockTemplateRepository_Expecter) Create(ctx interface{}, tt interface{}) *MockTemplateRepository_Create_Call {
	return &MockTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, tt)}
}

func (_c *MockTemplateRepository_Create_Call) Run(run func(ctx context.Context, tt *domain.TestTemplate)) *MockTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Create_Call) Return(err error) *MockTemplateRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tt *domain.TestTemplate) error) *MockTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Delete(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTemplateRepository_Delete_Call {
	return &MockTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTemplateRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) Return(err error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Filter(ctx context.Context, filter ports.TemplateFilter) ([]domain.TestTemplate, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.TemplateFilter) ([]domain.TestTemplate, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.TemplateFilter) []domain.TestTemplate); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.TemplateFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockTemplateRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.TemplateFilter
func (_e *MockTemplateRepository_Expecter) Filter(ctx interface{}, filter interface{}) *MockTemplateRepository_Filter_Call {
	return &MockTemplateRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter)}
}

func (_c *MockTemplateRepository_Filter_Call) Run(run func(ctx context.Context, filter ports.TemplateFilter)) *MockTemplateRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.TemplateFilter
		if args[1] != nil {
			arg1 = args[1].(ports.TemplateFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Filter_Call) Return(testTemplates []domain.TestTemplate, err error) *MockTemplateRepository_Filter_Call {
	_c.Call.Return(testTemplates, err)
	return _c
}

func (_c *MockTemplateRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter ports.TemplateFilter) ([]domain.TestTemplate, error)) *MockTemplateRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByID(ctx context.Context, id domain.ID) (*domain.TestTemplate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestTemplate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestTemplate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTemplateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTemplateRepository_GetByID_Call {
	return &MockTemplateRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTemplateRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) Return(testTemplate *domain.TestTemplate, err error) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(testTemplate, err)
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestTemplate, error)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByIDs(ctx context.Context, ids []domain.ID) ([]domain.TestTemplate, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) ([]domain.TestTemplate, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) []domain.TestTemplate); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.ID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockTemplateRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.ID
func (_e *MockTemplateRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockTemplateRepository_GetByIDs_Call {
	return &MockTemplateRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockTemplateRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []domain.ID)) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ID
		if args[1] != nil {
			arg1 = args[1].([]domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByIDs_Call) Return(testTemplates []domain.TestTemplate, err error) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Return(testTemplates, err)
	return _c
}

func (_c *MockTemplateRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []domain.ID) ([]domain.TestTemplate, error)) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Update(ctx context.Context, tt *domain.TestTemplate) error {
	ret := _mock.Called(ctx, tt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, tt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tt *domain.TestTemplate
func (_e *MockTemplateRepository_Expecter) Update(ctx interface{}, tt interface{}) *MockTemplateRepository_Update_Call {
	return &MockTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, tt)}
}

func (_c *MockTemplateRepository_Update_Call) Run(run func(ctx context.Context, tt *domain.TestTemplate)) *MockTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Update_Call) Return(err error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tt *domain.TestTemplate) error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
