// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTestSessionRepository creates a new instance of MockTestSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestSessionRepository {
	mock := &MockTestSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestSessionRepository is an autogenerated mock type for the TestSessionRepository type
type MockTestSessionRepository struct {
	mock.Mock
}

type MockTestSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestSessionRepository) EXPECT() *MockTestSessionRepository_Expecter {
	return &MockTestSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) CreateSession(ctx context.Context, session *domain.TestSession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestSession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTestSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.TestSession
func (_e *MockTestSessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockTestSessionRepository_CreateSession_Call {
	return &MockTestSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockTestSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session *domain.TestSession)) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestSession
		if args[1] != nil {
			arg1 = args[1].(*domain.TestSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_CreateSession_Call) Return(err error) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session *domain.TestSession) error) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) DeleteSession(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockTestSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTestSessionRepository_Expecter) DeleteSession(ctx interface{}, id interface{}) *MockTestSessionRepository_DeleteSession_Call {
	return &MockTestSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, id)}
}

func (_c *MockTestSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_DeleteSession_Call) Return(err error) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestSessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) GetSession(ctx context.Context, id domain.ID) (*domain.TestSession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *domain.TestSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestSession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestSession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestSessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockTestSessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTestSessionRepository_Expecter) GetSession(ctx interface{}, id interface{}) *MockTestSessionRepository_GetSession_Call {
	return &MockTestSessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockTestSessionRepository_GetSession_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_GetSession_Call) Return(testSession *domain.TestSession, err error) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Return(testSession, err)
	return _c
}

func (_c *MockTestSessionRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestSession, error)) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}
