// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/Valery223/Question-Bank/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuestionRepository creates a new instance of MockQuestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuestionRepository {
	mock := &MockQuestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuestionRepository is an autogenerated mock type for the QuestionRepository type
type MockQuestionRepository struct {
	mock.Mock
}

type MockQuestionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuestionRepository) EXPECT() *MockQuestionRepository_Expecter {
	return &MockQuestionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Create(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQuestionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionRepository_Expecter) Create(ctx interface{}, q interface{}) *MockQuestionRepository_Create_Call {
	return &MockQuestionRepository_Create_Call{Call: _e.mock.On("Create", ctx, q)}
}

func (_c *MockQuestionRepository_Create_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Create_Call) Return(err error) *MockQuestionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Delete(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQuestionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockQuestionRepository_Delete_Call {
	return &MockQuestionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockQuestionRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Delete_Call) Return(err error) *MockQuestionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockQuestionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Filter(ctx context.Context, filter QuestionFilter) ([]domain.Question, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QuestionFilter) ([]domain.Question, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QuestionFilter) []domain.Question); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QuestionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockQuestionRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QuestionFilter
func (_e *MockQuestionRepository_Expecter) Filter(ctx interface{}, filter interface{}) *MockQuestionRepository_Filter_Call {
	return &MockQuestionRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter)}
}

func (_c *MockQuestionRepository_Filter_Call) Run(run func(ctx context.Context, filter QuestionFilter)) *MockQuestionRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QuestionFilter
		if args[1] != nil {
			arg1 = args[1].(QuestionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Filter_Call) Return(questions []domain.Question, err error) *MockQuestionRepository_Filter_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestionRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter QuestionFilter) ([]domain.Question, error)) *MockQuestionRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) GetByID(ctx context.Context, id domain.ID) (*domain.Question, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.Question, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.Question); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockQuestionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockQuestionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockQuestionRepository_GetByID_Call {
	return &MockQuestionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockQuestionRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockQuestionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_GetByID_Call) Return(question *domain.Question, err error) *MockQuestionRepository_GetByID_Call {
	_c.Call.Return(question, err)
	return _c
}

func (_c *MockQuestionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.Question, error)) *MockQuestionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) GetByIDs(ctx context.Context, ids []domain.ID) ([]domain.Question, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []domain.Question
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) ([]domain.Question, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) []domain.Question); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.ID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuestionRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockQuestionRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.ID
func (_e *MockQuestionRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockQuestionRepository_GetByIDs_Call {
	return &MockQuestionRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockQuestionRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []domain.ID)) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ID
		if args[1] != nil {
			arg1 = args[1].([]domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_GetByIDs_Call) Return(questions []domain.Question, err error) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Return(questions, err)
	return _c
}

func (_c *MockQuestionRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []domain.ID) ([]domain.Question, error)) *MockQuestionRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockQuestionRepository
func (_mock *MockQuestionRepository) Update(ctx context.Context, q *domain.Question) error {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Question) error); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuestionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockQuestionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - q *domain.Question
func (_e *MockQuestionRepository_Expecter) Update(ctx interface{}, q interface{}) *MockQuestionRepository_Update_Call {
	return &MockQuestionRepository_Update_Call{Call: _e.mock.On("Update", ctx, q)}
}

func (_c *MockQuestionRepository_Update_Call) Run(run func(ctx context.Context, q *domain.Question)) *MockQuestionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Question
		if args[1] != nil {
			arg1 = args[1].(*domain.Question)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuestionRepository_Update_Call) Return(err error) *MockQuestionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuestionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, q *domain.Question) error) *MockQuestionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestSessionRepository creates a new instance of MockTestSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestSessionRepository {
	mock := &MockTestSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestSessionRepository is an autogenerated mock type for the TestSessionRepository type
type MockTestSessionRepository struct {
	mock.Mock
}

type MockTestSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestSessionRepository) EXPECT() *MockTestSessionRepository_Expecter {
	return &MockTestSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) CreateSession(ctx context.Context, session *domain.TestSession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestSession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockTestSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.TestSession
func (_e *MockTestSessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockTestSessionRepository_CreateSession_Call {
	return &MockTestSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockTestSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session *domain.TestSession)) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestSession
		if args[1] != nil {
			arg1 = args[1].(*domain.TestSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_CreateSession_Call) Return(err error) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session *domain.TestSession) error) *MockTestSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) DeleteSession(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestSessionRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockTestSessionRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTestSessionRepository_Expecter) DeleteSession(ctx interface{}, id interface{}) *MockTestSessionRepository_DeleteSession_Call {
	return &MockTestSessionRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, id)}
}

func (_c *MockTestSessionRepository_DeleteSession_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_DeleteSession_Call) Return(err error) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestSessionRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockTestSessionRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockTestSessionRepository
func (_mock *MockTestSessionRepository) GetSession(ctx context.Context, id domain.ID) (*domain.TestSession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *domain.TestSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestSession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestSession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestSessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockTestSessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTestSessionRepository_Expecter) GetSession(ctx interface{}, id interface{}) *MockTestSessionRepository_GetSession_Call {
	return &MockTestSessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockTestSessionRepository_GetSession_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestSessionRepository_GetSession_Call) Return(testSession *domain.TestSession, err error) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Return(testSession, err)
	return _c
}

func (_c *MockTestSessionRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestSession, error)) *MockTestSessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Create(ctx context.Context, tt *domain.TestTemplate) error {
	ret := _mock.Called(ctx, tt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, tt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tt *domain.TestTemplate
func (_e *MockTemplateRepository_Expecter) Create(ctx interface{}, tt interface{}) *MockTemplateRepository_Create_Call {
	return &MockTemplateRepository_Create_Call{Call: _e.mock.On("Create", ctx, tt)}
}

func (_c *MockTemplateRepository_Create_Call) Run(run func(ctx context.Context, tt *domain.TestTemplate)) *MockTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Create_Call) Return(err error) *MockTemplateRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tt *domain.TestTemplate) error) *MockTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Delete(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTemplateRepository_Delete_Call {
	return &MockTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTemplateRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) Return(err error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Filter(ctx context.Context, filter TemplateFilter) ([]domain.TestTemplate, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TemplateFilter) ([]domain.TestTemplate, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TemplateFilter) []domain.TestTemplate); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TemplateFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockTemplateRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter TemplateFilter
func (_e *MockTemplateRepository_Expecter) Filter(ctx interface{}, filter interface{}) *MockTemplateRepository_Filter_Call {
	return &MockTemplateRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter)}
}

func (_c *MockTemplateRepository_Filter_Call) Run(run func(ctx context.Context, filter TemplateFilter)) *MockTemplateRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TemplateFilter
		if args[1] != nil {
			arg1 = args[1].(TemplateFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Filter_Call) Return(testTemplates []domain.TestTemplate, err error) *MockTemplateRepository_Filter_Call {
	_c.Call.Return(testTemplates, err)
	return _c
}

func (_c *MockTemplateRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter TemplateFilter) ([]domain.TestTemplate, error)) *MockTemplateRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByID(ctx context.Context, id domain.ID) (*domain.TestTemplate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.TestTemplate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.TestTemplate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTemplateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockTemplateRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTemplateRepository_GetByID_Call {
	return &MockTemplateRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTemplateRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) Return(testTemplate *domain.TestTemplate, err error) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(testTemplate, err)
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.TestTemplate, error)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByIDs(ctx context.Context, ids []domain.ID) ([]domain.TestTemplate, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []domain.TestTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) ([]domain.TestTemplate, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ID) []domain.TestTemplate); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TestTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.ID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockTemplateRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []domain.ID
func (_e *MockTemplateRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockTemplateRepository_GetByIDs_Call {
	return &MockTemplateRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockTemplateRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []domain.ID)) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ID
		if args[1] != nil {
			arg1 = args[1].([]domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByIDs_Call) Return(testTemplates []domain.TestTemplate, err error) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Return(testTemplates, err)
	return _c
}

func (_c *MockTemplateRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []domain.ID) ([]domain.TestTemplate, error)) *MockTemplateRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Update(ctx context.Context, tt *domain.TestTemplate) error {
	ret := _mock.Called(ctx, tt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TestTemplate) error); ok {
		r0 = returnFunc(ctx, tt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tt *domain.TestTemplate
func (_e *MockTemplateRepository_Expecter) Update(ctx interface{}, tt interface{}) *MockTemplateRepository_Update_Call {
	return &MockTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, tt)}
}

func (_c *MockTemplateRepository_Update_Call) Run(run func(ctx context.Context, tt *domain.TestTemplate)) *MockTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TestTemplate
		if args[1] != nil {
			arg1 = args[1].(*domain.TestTemplate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Update_Call) Return(err error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tt *domain.TestTemplate) error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
